export const IC_LOGO = require('./icons/ic_logo.png')
export const IC_SMALLLOGO = require('./icons/ic_smalllogo.png')
export const IC_MENU = require('./icons/ic_menu.png')
export const IC_CAM = require('./icons/ic_camera.png')
export const IC_LIST = require('./icons/ic_list.png')
export const IC_HISTORY = require('./icons/ic_history.png')
export const IC_ADDBTN = require('./icons/ic_addbtn.png')
export const IC_SEARCH = require('./icons/ic_search.png')
export const IC_ADDCOLLECTION = require('./icons/ic_addcollection.png')
export const IC_DROP = require('./icons/ic_drop.png')
export const IC_ITEMCOLLECTION = require('./icons/ic_itemcollection.png')
export const IC_BACK = require('./icons/ic_back.png')
export const IC_EDITPROFILEIMG = require('./icons/ic_editprofileimg.png')
export const IC_CALL = require('./icons/ic_call.png')
export const IC_MESSAGE = require('./icons/ic_message.png')
export const IC_FACETIME = require('./icons/ic_facetime.png')
export const IC_EMAIL = require('./icons/ic_email.png')
export const IC_GREENADD = require('./icons/ic_greenadd.png')
export const IC_REDDELETE = require('./icons/ic_reddelete.png')
export const IC_MORE_INFO = require('./icons/ic_more-info.png')
export const IC_MISS_CALL = require('./icons/ic_miss-call.png')
export const IC_MISS_FACETIME = require('./icons/ic_miss-facetime.png')

export const IMG_HOMEBG = require('./images/img_homebg.png')
export const IMG_NAVBG = require('./images/img_nav-bg.png')
export const IMG_DEFAULTPROFILE = require('./images/img_defaultprofile.png')

export const IMG_PROFILE = require('./images/logo.jpg')